# Generated by Django 5.2.10 on 2026-01-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeshiftArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('stream_url', models.URLField(max_length=500)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeshift_archives', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Timeshift Archive',
                'verbose_name_plural': 'Timeshift Archives',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['channel', 'start_time'], name='timeshift_t_channel_df16be_idx')],
            },
        ),
    ]
