# Generated by Django 5.2.10 on 2026-07-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='STORAGE_NAME configurado en el config.php del servidor', max_length=100, unique=True)),
                ('role', models.CharField(choices=[('archive', 'Archivo/catchup (storage1)'), ('records', 'Grabaciones de cliente (record1)'), ('both', 'Ambos')], default='both', max_length=10)),
                ('api_url', models.URLField(help_text='Base REST del storage, ej. http://storage1.quattre.com/storage/ (ahí viven rest.php y get.php)', max_length=300)),
                ('playback_url', models.URLField(blank=True, help_text='Base pública para reproducir (get.php). Si se deja vacía se usa api_url', max_length=300)),
                ('token', models.CharField(blank=True, help_text='Token compartido: se envía como Bearer y se valida en chk_storage_token.php', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última vez que el storage pidió sus tareas de archivo', null=True)),
            ],
            options={
                'verbose_name': 'Storage Server',
                'verbose_name_plural': 'Storage Servers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='filename',
            field=models.CharField(blank=True, help_text='Fichero .mpg devuelto por el grabador', max_length=300),
        ),
        migrations.AddField(
            model_name='recording',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='pvr.storageserver'),
        ),
    ]
