# Generated by Django 5.2.10 on 2026-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvr', '0002_storageserver_recording_filename_recording_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='container',
            field=models.CharField(choices=[('ts', 'MPEG-TS'), ('hls', 'HLS')], default='ts', help_text='Formato con el que se grabo. Se fija al enviarla al grabador, para que las grabaciones antiguas se sigan reproduciendo despues de migrar.', max_length=4),
        ),
        migrations.AddField(
            model_name='storageserver',
            name='archive_path',
            field=models.CharField(default='archive_hls', help_text='Subdirectorio (servido por nginx con autoindex json) donde el grabador deja los segmentos HLS del archivo', max_length=100),
        ),
        migrations.AddField(
            model_name='storageserver',
            name='records_hls',
            field=models.BooleanField(default=False, help_text='El grabador de este servidor ya escribe HLS en vez de MPEG-TS. Se activa canal a canal; mientras esté desactivado todo sigue como hasta ahora.'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='filename',
            field=models.CharField(blank=True, help_text='Fichero devuelto por el grabador', max_length=300),
        ),
    ]
