# Generated by Django 5.2.10 on 2026-07-28 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channel_archive_hls_since'),
        ('epg', '0001_initial'),
        ('pvr', '0003_recording_container_storageserver_archive_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['status', 'start_time'], name='pvr_recordi_status_ecb84f_idx'),
        ),
    ]
