# Generated by Django 5.2.10 on 2026-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvr', '0004_recording_pvr_recordi_status_ecb84f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageserver',
            name='ssh_host',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storageserver',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='storageserver',
            name='ssh_user',
            field=models.CharField(default='quattre', max_length=50),
        ),
    ]
