# Generated by Django 5.2.10 on 2026-01-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial_user'),
        ('channels', '0001_initial_user'),
        ('devices', '0001_initial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='channel_packages',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='channels.channelpackage'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.tariff'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
