# Generated by Django 5.2.10 on 2026-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_user'),
        ('channels', '0001_initial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text='Canales individuales incluidos en esta tarifa', related_name='tariffs', to='channels.channel'),
        ),
    ]
