# Generated by Django 5.2.10 on 2026-01-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_channels_to_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['name'], 'verbose_name': 'Tariff', 'verbose_name_plural': 'Tariffs'},
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='price',
        ),
    ]
