# Generated by Django 5.2.10 on 2026-01-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('mac_address', models.CharField(db_index=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('mag', 'MAG STB'), ('android', 'Android'), ('ios', 'iOS'), ('smart_tv', 'Smart TV'), ('web', 'Web Browser'), ('other', 'Other')], default='mag', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=50)),
                ('language', models.CharField(default='es', max_length=5)),
                ('volume', models.PositiveIntegerField(default=50)),
                ('brightness', models.PositiveIntegerField(default=100)),
                ('last_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_watched_by', to='channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('reload', 'Reload Portal')], default='info', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, help_text='Leave empty to send to all devices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='devices.device')),
                ('user', models.ForeignKey(blank=True, help_text='Send to all devices of this user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Message',
                'verbose_name_plural': 'Device Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
