# Generated by Django 5.2.10 on 2026-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uid',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador propio del aparato, para los que no tienen MAC (la app de LG, el navegador). Permite distinguir dos teles del mismo usuario en vez de que compartan ficha.', max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mag', 'MAG STB'), ('android', 'Android'), ('ios', 'iOS'), ('lg', 'LG TV'), ('samsung', 'Samsung TV'), ('smart_tv', 'Smart TV'), ('web', 'Web Browser'), ('other', 'Other')], default='mag', max_length=20),
        ),
    ]
