# Generated by Django 5.2.10 on 2026-01-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='vod/seasons/')),
                ('poster_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('tmdb_id', models.CharField(blank=True, max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='vod/series/posters/')),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='vod/series/backdrops/')),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('genres', models.CharField(blank=True, max_length=200)),
                ('cast', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_adult', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='vod/episodes/')),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('stream_url', models.URLField(max_length=500)),
                ('stream_type', models.CharField(default='hls', max_length=10)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='vod.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='vod.series'),
        ),
        migrations.CreateModel(
            name='VodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='vod/categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_adult', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vod.vodcategory')),
            ],
            options={
                'verbose_name': 'VOD Category',
                'verbose_name_plural': 'VOD Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='vod.vodcategory'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('tmdb_id', models.CharField(blank=True, max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='vod/posters/')),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='vod/backdrops/')),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('stream_url', models.URLField(max_length=500)),
                ('stream_type', models.CharField(choices=[('hls', 'HLS'), ('dash', 'DASH'), ('mp4', 'MP4')], default='hls', max_length=10)),
                ('genres', models.CharField(blank=True, help_text='Comma-separated', max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('cast', models.TextField(blank=True, help_text='Comma-separated')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('is_hd', models.BooleanField(default=False)),
                ('is_4k', models.BooleanField(default=False)),
                ('is_adult', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='vod.vodcategory')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='vod.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='vod.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch History',
                'verbose_name_plural': 'Watch History',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'number')},
        ),
    ]
