# Generated by Django 5.2.10 on 2026-01-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Channel Package',
                'verbose_name_plural': 'Channel Packages',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_adult', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='channels.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='channels/logos/')),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL')),
                ('stream_url', models.URLField(max_length=500)),
                ('stream_type', models.CharField(choices=[('hls', 'HLS'), ('dash', 'DASH'), ('rtsp', 'RTSP'), ('http', 'HTTP/HTTPS'), ('udp', 'UDP Multicast')], default='hls', max_length=10)),
                ('backup_stream_url', models.URLField(blank=True, max_length=500)),
                ('has_epg', models.BooleanField(default=True)),
                ('has_timeshift', models.BooleanField(default=True)),
                ('has_catchup', models.BooleanField(default=True)),
                ('has_recording', models.BooleanField(default=True)),
                ('is_hd', models.BooleanField(default=False)),
                ('is_4k', models.BooleanField(default=False)),
                ('is_adult', models.BooleanField(default=False)),
                ('epg_id', models.CharField(blank=True, db_index=True, help_text='EPG channel ID for program guide', max_length=100)),
                ('timeshift_hours', models.PositiveIntegerField(default=24, help_text='Hours of timeshift/catchup available')),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('language', models.CharField(blank=True, help_text='ISO language code', max_length=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='channels.category')),
                ('packages', models.ManyToManyField(blank=True, related_name='channels', to='channels.channelpackage')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ChannelStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='e.g., HD, SD, Mobile', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('stream_type', models.CharField(choices=[('hls', 'HLS'), ('dash', 'DASH'), ('rtsp', 'RTSP'), ('http', 'HTTP/HTTPS'), ('udp', 'UDP Multicast')], default='hls', max_length=10)),
                ('quality', models.CharField(choices=[('4k', '4K Ultra HD'), ('1080p', '1080p Full HD'), ('720p', '720p HD'), ('480p', '480p SD'), ('360p', '360p'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = preferred')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Channel Stream',
                'verbose_name_plural': 'Channel Streams',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['order', '-created_at'],
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
