# Generated by Django 5.2.10 on 2026-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_multicast_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='archive_hls_since',
            field=models.DateTimeField(blank=True, help_text='Momento en que este canal empezo a archivarse en HLS. Lo anterior a esta fecha sigue sirviendose del archivo antiguo en MPEG-TS, asi que la migracion no deja huecos. Vacio = todavia se archiva en MPEG-TS.', null=True),
        ),
    ]
