# Generated by Django 5.2.10 on 2026-07-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channel_archive_hls_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='cdn10, cdn11...', max_length=50, unique=True)),
                ('hls_base_url', models.URLField(help_text='Base del HLS, ej. http://cdn10.quattre.com:1500/hls/', max_length=300)),
                ('ssh_host', models.CharField(blank=True, max_length=100)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_user', models.CharField(default='quattre', max_length=50)),
                ('systemd_unit', models.CharField(default='ffmpeg-hls@', help_text='Plantilla systemd; se le añade el nombre del canal en el CDN', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CDN',
                'verbose_name_plural': 'CDNs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='cdn_name',
            field=models.CharField(blank=True, help_text='Nombre del canal en el CDN (el de ffmpeg-hls@<nombre> y el del directorio HLS). Si se deja vacío se deduce de la URL.', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='cdn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='channels.cdnserver'),
        ),
    ]
