# Generated by Django 5.2.10 on 2026-01-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpgSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='XMLTV source URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('update_interval', models.PositiveIntegerField(default=3600, help_text='Update interval in seconds')),
                ('auto_update', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EPG Source',
                'verbose_name_plural': 'EPG Sources',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epg_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('episode_title', models.CharField(blank=True, max_length=500)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('poster', models.URLField(blank=True, max_length=500)),
                ('icon', models.URLField(blank=True, max_length=500)),
                ('is_live', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_premiere', models.BooleanField(default=False)),
                ('has_subtitles', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['channel', 'start_time'], name='epg_program_channel_519b32_idx'), models.Index(fields=['epg_id', 'start_time'], name='epg_program_epg_id_84a6d3_idx')],
            },
        ),
    ]
