# Sirve HLS desde /dev/shm con headers correctos y CORS
server {
    listen 1500;
    server_name cdn10.quattre.com;  # cámbialo

    # Evita que Nginx intente comprimir TS/M3U8 (no aporta y puede romper players)
    gzip off;

    # Raíz donde ffmpeg deja los HLS
    root /dev/shm;
    # Acceso directo: http://hls.midominio.com/hls/canal1/index.m3u8
    location ~* ^/hls/.*\.ts$ {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Headers Range;
        add_header Access-Control-Expose-Headers Content-Length,Content-Range;

        types { video/mp2t ts; }
        default_type video/mp2t;

        add_header Cache-Control "public, max-age=60, immutable";
        expires 60s;

        open_file_cache max=20000 inactive=30s;
        sendfile on;
        tcp_nopush on;
        # aio off;   # <- simplemente no lo uses
        try_files $uri =404;
    }


    # Opcional: status de Nginx (si compilas stub_status) para monitoring
    # location /nginx_status { stub_status; allow 127.0.0.1; deny all; }
}

